name: 'Git Deploy Action'
description: 'Deploy a direction to an git repo'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  lfs:
    description: 'Whether to download Git-LFS files'
    required: false
    default: 'false'
  ssh-key:
    description: 'Deploy key'
    required: false
  src-dir:
    description: 'The src dir for sync.'
    required: false
  branch:
    description: 'The des branch for sync.'
    required: false
    default: 'master'
  des-dir:
    description: 'The des dir for sync.'
    required: false
  repo-url:
    description: 'The url for des repo.'
    required: false
  user-name:
    description: 'Set Git user.name'
    required: false
  user-email:
    description: 'Set Git user.email'
    required: false
  commit-message:
    description: 'Set a custom commit message with a triggered commit hash'
    required: false
  keep-files:
    description: 'If existing files in the publish branch should be not removed before deploying'
    required: false
    default: 'false'
  force-orphan:
    description: 'Keep only the latest commit on a GitHub Pages branch'
    required: false
    default: 'false'
