name: Test git-sync
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./git-sync
        with:
          ssh-key: ${{ secrets.TEST }}
          repo-url: github.com
          include-branches: master;test
