name: Test git-sync
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ./git-sync
        name: Sync to Coding.net
        with:
          ssh-key: ${{ secrets.CODING_DEPLOY }}
          repo-url: git@e.coding.net:lippen/workflows/workflows.git
          include-branches: master;main;test
      - uses: ./git-sync
        name: Sync to Gitee.com
        with:
          ssh-key: ${{ secrets.GITEE_DEPLOY }}
          repo-url: git@gitee.com:okou19900722/workflows.git
      - uses: ./git-sync
        name: Sync to codechina.csdn.net
        with:
          ssh-key: ${{ secrets.CSDN_DEPLOY }}
          repo-url: git@codechina.csdn.net:okou19900722/workflows.git
          exclude-branches: test
      - uses: ./git-sync
        name: Sync to Gitlab.com
        with:
          ssh-key: ${{ secrets.GITLAB_DEPLOY }}
          repo-url: git@gitlab.com:okou19900722/workflows.git
          include-branches: master;main;test
          exclude-branches: test
